# Change these first
owner: acidflash # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

sites:
  - name: Connect.ax
    url: https://www.connect.ax
  - name: Webmail
    url: https://webmail.ipconnect.fi
  - name: Webhost
    url: https://webhost.connect.ax:8080
  - name: dns.connect.ax
    url: dns.connect.ax
    port: 53
    check: "tcp-ping"
  - name: dns2.ipconnect.fi
    url: dns2.ipconnect.fi
    port: 53
    check: "tcp-ping"
  - name: dns3.ipconnect.fi
    url: dns3.ipconnect.fi
    port: 53
    check: "tcp-ping"
  - name: dns4.ipconnect.fi
    url: dns4.ipconnect.fi
    port: 53
    check: "tcp-ping"
  - name: smtp3.ipconnect.fi
    url: smtp3.ipconnect.fi
    port: 25
    check: "tcp-ping" 
  - name: smtp10.ipconnect.fi
    url: smtp10.ipconnect.fi
    port: 25
    check: "tcp-ping" 
  - name: smtp11.ipconnect.fi
    url: smtp11.ipconnect.fi
    port: 25
    check: "tcp-ping" 
  - name: smtp12.ipconnect.fi
    url: smtp12.ipconnect.fi
    port: 25
    check: "tcp-ping" 

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  baseUrl: /upptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  introMessage: This is a sample status page which uses **real-time** data from our [GitHub repository](https://github.com/upptime/upptime). No server required — just GitHub Actions, Issues, and Pages. [**Get your own for free**](https://github.com/upptime/upptime)
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
